remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme

title: Academic Panic
description: Tired of failing all your classes all alone? Join Academic Panic -- at least you won't be alone!
